use import="Environment"

@{
    if (E("APPVEYOR") == null || E("APPVEYOR_REPO_TAG") == "False") {
        E("K_BUILD_VERSION", "beta-" + E("K_BUILD_VERSION"));
    }
}

var AUTHORS='David Driscoll'

use-standard-lifecycle
k-standard-goals
